AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

Metrics/MethodLength:
  CountAsOne:
    - heredoc
